### ISSUE TITLE
Dependency compile 'com.github.pakoito:RxSealedUnions:1.0.1' not found

### ISSUE THREAD

**Issue by Zhuinden** [pakoito/RxSealedUnions#3]
I added `compile 'com.github.pakoito:RxSealedUnions:1.0.1'` as a dependency, but it says it's not found.

I added jitpack.io previously, so that's weird.

**Comment by pakoito** [comment]
I had to nuke it due to Jitpack issues. You need to add 1.0.2, let me update the README.

**Comment by pakoito** [comment]
Fixed readme, thanks for the tip!
