### ISSUE TITLE
Support for more that 9 types?

### ISSUE THREAD

**Issue by mariobat88** [pakoito/RxSealedUnions#5]
Not an issue, but what if I have more than 9 states which I want to handle?

**Comment by pakoito** [comment]
It can be written, I decided not to do it until someone required it.

Worst case you can always nest it Union9<Union9<...>> indefinitely :D

**Comment by mariobat88** [comment]
yes I noticed that I can nest it. I'm developing an app with MVI on Android where I wan't to get rid of switch statements in the reducer. I could write larger unions myself though?
Nice library btw :)

**Comment by pakoito** [comment]
Yeah, it's a bit boilerplateish but it can be done with copy&replace. You need:

Union 10: https://github.com/pakoito/RxSealedUnions/blob/master/rxsealedunions/src/main/java/com/pacoworks/rxsealedunions/Union9.java

generic/Union10First..Tenth:
https://github.com/pakoito/RxSealedUnions/blob/master/rxsealedunions/src/main/java/com/pacoworks/rxsealedunions/generic/Union9First.java
https://github.com/pakoito/RxSealedUnions/blob/master/rxsealedunions/src/main/java/com/pacoworks/rxsealedunions/generic/Union9Second.java
...
https://github.com/pakoito/RxSealedUnions/blob/master/rxsealedunions/src/main/java/com/pacoworks/rxsealedunions/generic/Union9Ninth.java

And a generic/factory:
https://github.com/pakoito/RxSealedUnions/blob/master/rxsealedunions/src/main/java/com/pacoworks/rxsealedunions/generic/GenericUnions.java#L248

If you'd like to PR them afterwards I'll happily add them :)

**Comment by mariobat88** [comment]
Okay. I'll make a PR if I get the need to create them. Thank you!

**Comment by pakoito** [comment]
Cool, should we close this issue?

**Comment by mariobat88** [comment]
Yes, we can close it. Thanks
